### PR TITLE
Accept GOOGLE_APPLICATION_CREDENTIALS + don't bind host network + use ATTEMPTS parameter

### PR DESCRIPTION
**Pull request by daaain**
I had a bit of a nightmare getting this action going, but while debugging to make it work I found a few things to improve on:
- use `attempts` parameter in the `wait.sh` loop – currently it's hardcoded to 10
- if `GOOGLE_APPLICATION_CREDENTIALS` env var is present use it, so if you use `google-github-actions/auth@v2` this action will "just work" without any config
- print authentication method so you know which one was picked by the condition
- remove volume when authenticating with token as it's not used
- stop binding to host network and also limit port binding to connections from localhost to make it simpler and more secure
- print container logs if connection wasn't successful to help with debugging
- minor edits in README
- improve conditions for auth checking so that it actually checks if the credentials file exists and prints an error message if can't find any of the 3 auth options

### CODE REVIEW

**Comment by ahmadnassri** [comment]
thank you! i'll review today and merge if there are no issues ...

note: the README source is actually under `docs/README.md` the one in the root is auto generated with `make readme` _(just a personal style setup, if you don't have a chance to make the necessary adjustments, I'll take care of them when I review later today)_

**Comment by daaain** [comment]
> thank you! i'll review today and merge if there are no issues ...
> 
> note: the README source is actually under `docs/README.md` the one in the root is auto generated with `make readme` _(just a personal style setup, if you don't have a chance to make the necessary adjustments, I'll take care of them when I review later today)_

Ah right, didn't notice that, was just looking at the previous PR. Updated the README template sources and also had a look at the linter output and fixed some Bash quoting issues. There were a few linting issues left, but don't think this branch broke them so eventually gave up 😅 see https://github.com/ahmadnassri/action-google-cloud-sql-proxy/pull/67/commits/0b76049df85a6deb2e8e1700c01714cc8193c058

**Comment by ahmadnassri** [comment]
I had to edit your commit messages and rebase locally _(because of commit lint action, I should fix the workflows here to allow them to run on PRs...)_, your changes _(with your authorship)_ are on main branch now, so I'll manually close this PR.

thank you!

**Comment by ahmadnassri** [comment]
now live as [v1.4.0](https://github.com/ahmadnassri/action-google-cloud-sql-proxy/releases/tag/v1.4.0)

**Pull request closed without merging**
